#!/bin/zsh
#autoload
# If needed recompile zsh files in plugin folders
# $1 = folder to compile

function compile_plugins {
  local folder=${1}
  for file in ${folder}/**/*.zsh; do
    if [[ -s ${file} && ( ! -s ${file}.zwc || ${file} -nt ${file}.zwc) ]]; then
      zcompile "${file}" 2>/dev/null
    fi
  done
  unset folder
}
compile_plugins "$@"
