#!/bin/zsh
#autoload
# List modules loaded
# $1 = -l for full file name
# $2 =
function list_modules {

  printf "Modules:\n"
  for module in $_ZMOD_modules; do
    case "$1" in
      -l)
        printf "${module}\n"
        ;;
      -d)
        printf "${module}\n" | awk {'printf ("%6.3f ms:    ", ($3-$2)*1000)'}
        printf "${module:t:r}\n"
        ;;
      -dl)
        printf "${module}\n" | awk {'printf ("%6.3f ms:    ", ($3-$2)*1000)'}
        printf "${module}\n" | awk {'print $4'}
        ;;
      *)
        printf "${module:t:r}\n"
        ;;
    esac
  done
}
list_modules "$@"
