#!/bin/zsh
#autoload

# List modules loaded
# $1 = option

@list() {

  # Add STARTUP_Z=$EPOCHREALTIME at the end of your .zshrc
  local -F startup_p=$STARTUP_Z
  printf "Modules:\n"

  for module in $_ZMOD_modules; do
    # Split module string into array
    module_info=(${(s. .)module})
    local name=$module_info[1]
    local mod_path=$module_info[4]
    local -F start=$module_info[2]
    local -F end=$module_info[3]
    local -F took_ms='1e3 * (end - start)'
    local -F startup_ms='end - startup_p'

    case "$1" in
      -f)
        printf "${module}\n"
        ;;
      -l)
        printf "$mod_path\n"
        ;;
      -d)
        printf "%6.3f ms:\t$name\n" $took_ms
        ;;
      -dl)
        printf "%6.3f ms:\t$mod_path\n" $took_ms
        ;;
      -s)
        printf "%6.3f sec:\t$name\n" $startup_ms
        ;;
      *)
        printf "${name:t}\n"
        ;;
    esac
  done
}
