#!/bin/zsh
#autoload
# Source files and recompile them if needed
# $1 = file to source
# $2 = module name
function source_compile {

  local file="$1"
  local name="$2"
  local -F start=EPOCHREALTIME

  # We can't compile files that do not exist
  [[ ! -e $file ]] && return

  # Check if the file is newer than it's compiled version, and recompile if necessary
  [[ ${file}.zwc -nt ${file} ]] || @zcompile ${file}

  builtin source "${file}"

  _ZMOD_modules+="${name} ${start} $EPOCHREALTIME ${file}"
  unset name file start

}
source_compile "$@"
