#!/bin/zsh
#autoload
# Source files and recompile them if needed
# $1 = file to source
# $2 = module name
function source_compile {

  local file="$1"
  local start=$EPOCHREALTIME

  # We can't compile files that do not exist
  [[ ! -e $file ]] && return

  # Check if the file is newer than it's compiled version, and recompile if necessary
  if [[ -s ${file} && ( ! -s ${file}.zwc || ${file} -nt ${file}.zwc) ]]; then
    zcompile "${file}" 2>/dev/null
  fi

  builtin source "${file}"

  _ZMOD_modules+="${file:t:r} ${start} $EPOCHREALTIME ${file}"
  unset file start
}
source_compile "$@"
