#!/bin/zsh
#autoload

# Update git repos in specified folder and subfolders
# $1 = folder to start the search


@update() {

  if [[ $#1 -eq 0 ]]; then
    print -P "%F{red}Please provide a path%f"
    return 0
  fi

  local folder=$1
  local -a git_repos
  git_repos=( ${folder:A}/**/.git )
  git_repos=( ${git_repos:h} )

  print
  print -P "%F{green}Update git repositories in ${folder}:%f"
  local repo
  for repo in $git_repos; do
    local git_repo=$(git -C ${repo} config --get remote.origin.url)
    print
    print -P "Update: %F{yellow}${git_repo}%f"
    print -P "Located: %F{cyan}${repo}%f"
    git -C $repo pull
  done
  unset folder git_repos git_repo repo

  @zcompile $PLUGIN_DIR/zsh-users/zsh-syntax-highlighting/{zsh-syntax-highlighting.zsh,highlighters/*/*.zsh}
  @zcompile $PLUGIN_DIR/zsh-users/zsh-autosuggestions/{zsh-autosuggestions.zsh,src/**/*.zsh}
  @zcompile $PLUGIN_DIR/zsh-users/zsh-history-substring-search/zsh-history-substring-search.zsh
  @zcompile $PLUGIN_DIR/zmod/zmod.zsh

}
