#!/bin/zsh
#autoload

# Zcompile file(s)
# $1 = file(s) to compile

@zcompile() {
    local file
    for file; do
        [[ "${file}.zwc" -nt "$file" ]] || sched +1 zcompile -R -- "$file".zwc "$file"
    done
}
